import { Option } from "../../Types/Option";

export const options: Option[] = [
  { label: "JavaScript" },
  { label: "Python" },
  { label: "Java" },
  { label: "C#" },
  { label: "C++" },
  { label: "PHP" },
  { label: "Ruby" },
  { label: "Swift" },
  { label: "Go" },
  { label: "Kotlin" },
  { label: "TypeScript" },
  { label: "Vue.js" },
  { label: "ReactJS" },
  { label: "Angular" },
  { label: "Node.js" },
  { label: "Express.js" },
  { label: "Django" },
  { label: "Spring Boot" },
  { label: "Laravel" },
  { label: "ASP.NET" },
  { label: "Flutter" },
  { label: "React Native" },
  { label: "Ionic" },
  { label: "Xcode" },
  { label: "Android Studio" },
  { label: "Visual Studio Code" },
  { label: "PyCharm" },
  { label: "WebStorm" },
  { label: "IntelliJ IDEA" },
  { label: "Eclipse" },
  { label: "Atom" },
  { label: "Sublime Text" },
  { label: "Git" },
  { label: "GitHub" },
];
